# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(376, 801)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setStyleSheet("background-color:#22222e")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 381, 311))
        self.frame.setStyleSheet("background-color:#fb5b5d")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(100, 40, 203, 29))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(110, 90, 151, 121))
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("pngwing.com.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(130, 220, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white")
        self.label_3.setObjectName("label_3")
        self.input_valute_from = QtWidgets.QLineEdit(self.centralwidget)
        self.input_valute_from.setGeometry(QtCore.QRect(50, 340, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(14)
        self.input_valute_from.setFont(font)
        self.input_valute_from.setStyleSheet("background-color:#22222e;\n"
                                             "border:2px solid white;\n"
                                             "border-radius:30;\n"
                                             "color:white;")
        self.input_valute_from.setText("")
        self.input_valute_from.setAlignment(QtCore.Qt.AlignCenter)
        self.input_valute_from.setObjectName("input_valute_from")
        self.input_money = QtWidgets.QLineEdit(self.centralwidget)
        self.input_money.setGeometry(QtCore.QRect(50, 430, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(14)
        self.input_money.setFont(font)
        self.input_money.setStyleSheet("background-color:#22222e;\n"
                                       "border:2px solid white;\n"
                                       "border-radius:30;\n"
                                       "color:white;")
        self.input_money.setText("")
        self.input_money.setAlignment(QtCore.Qt.AlignCenter)
        self.input_money.setObjectName("input_money")
        self.input_valute_to = QtWidgets.QLineEdit(self.centralwidget)
        self.input_valute_to.setGeometry(QtCore.QRect(50, 520, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(14)
        self.input_valute_to.setFont(font)
        self.input_valute_to.setStyleSheet("background-color:#22222e;\n"
                                           "border:2px solid white;\n"
                                           "border-radius:30;\n"
                                           "color:white;")
        self.input_valute_to.setText("")
        self.input_valute_to.setAlignment(QtCore.Qt.AlignCenter)
        self.input_valute_to.setObjectName("input_valute_to")
        self.result = QtWidgets.QLineEdit(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(50, 610, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(14)
        self.result.setFont(font)
        self.result.setStyleSheet("background-color:#22222e;\n"
                                  "border:2px solid white;\n"
                                  "border-radius:30;\n"
                                  "color:white;")
        self.result.setText("")
        self.result.setAlignment(QtCore.Qt.AlignCenter)
        self.result.setObjectName("result")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(60, 710, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
                                      "    color: white;\n"
                                      "    background-color: #fb5b5d;\n"
                                      "    border-radius:20;\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed{\n"
                                      "    background-color: #f24244\n"
                                      "}\n"
                                      "")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Конвертер валют"))
        self.label_3.setText(_translate("MainWindow", "RUB - USD"))
        self.pushButton.setText(_translate("MainWindow", "Конвертировать"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
