# Generated by Django 3.2.5 on 2022-01-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211116_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=128, unique=True, verbose_name='артикул')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='цена')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('title', models.CharField(blank=True, max_length=256, verbose_name='заголовок страницы (<title>)')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('related_products', models.ManyToManyField(blank=True, to='mainapp.Product', verbose_name='связанные продукты')),
            ],
        ),
    ]
