# Generated by Django 3.2.6 on 2021-08-30 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Название статика')),
            ],
            options={
                'verbose_name': 'Статик',
                'verbose_name_plural': 'Статики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Имя')),
                ('nick', models.CharField(max_length=50, verbose_name='Ник в игре')),
                ('proffesion', models.CharField(max_length=50, null=True, verbose_name='Спек')),
                ('static_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.namestatic', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ['name'],
            },
        ),
    ]
