# Generated by Django 3.2.6 on 2021-08-30 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='namestatic',
            options={'ordering': ['-name'], 'verbose_name': 'Статик', 'verbose_name_plural': 'Статики'},
        ),
        migrations.AlterField(
            model_name='player',
            name='static_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.namestatic', verbose_name='Название статика'),
        ),
    ]
